### ISSUE TITLE
I'm not sure if it's an issue with the template, but I recieve 404 NOT_FOUND errors when deploying to vercel

### ISSUE THREAD

**Issue by ethanAthompson** [friendlymatthew/create-leptos-csr#2]
![image](https://github.com/friendlymatthew/create-leptos-csr/assets/140981795/bd9cbefc-2577-4ee0-9ccc-1442492c1b78)

Did I deploy my project wrong? or maybe its some type of configuration I overlooked.

It was working for me before, but ever since I did something...

**Comment by friendlymatthew** [comment]
Hey @ethanAthompson,

To deploy with vercel, you'll want to link the root directory to your `/dist` folder.

Also, in your `Build and Output Settings`, make sure to specify the output directory as `dist`.

Here's a screenshot for reference:

My leptos project is called demo, and there is a parent directory called examples. Regardless, just route to your `dist/`

<img width="948" alt="Screen Shot 2024-02-11 at 10 16 12 PM" src="https://github.com/friendlymatthew/create-leptos-csr/assets/38759997/7140fcc9-1e88-4af9-a2fa-62af804c5e8b">
